PrepaGuide-main/app/models.py
from . import db
from flask_login import UserMixin

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    location = db.Column(db.String(150))
    section = db.Column(db.String(150))
    rank = db.Column(db.Integer)
    tables = db.relationship('Table')
    
    def to_dict(self):
        return {
            "id": self.id, 
            "username": self.username,
            "location": self.location,
            "section": self.section,
            "rank": self.rank
        }
    
class Table(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class Data(db.Model):
    __bind_key__ = 'data'
    id = db.Column(db.Integer, primary_key=True)
    section = db.Column(db.String(2))
    ecole = db.Column(db.String(150))
    filiere = db.Column(db.String(150))
    location = db.Column(db.String(150))
    category = db.Column(db.String(150))
    last_rank = db.Column(db.Integer)
    

PrepaGuide-main/app/forms.py
from flask import flash
from werkzeug.security import check_password_hash, generate_password_hash
from .models import User

def valid_sign_up(request):
    username = request.form['username']
    password = request.form['password']
    confirm_password = request.form['confirm_password']
    location = request.form['location']
    section = request.form['sections']
    rank = request.form['rank']
    
    user = User.query.filter_by(username=username).first()
    if user:
        flash("username already used")
    elif len(username)<3:
        flash("username must be greater than 3 characters")
    elif len(password)<5:
        flash("password must be at least 6 chars")
    elif password != confirm_password:
        flash("passwords dont match")
    else:
        new_user = User(
            username=username,
            password = generate_password_hash(password),
            location = location,
            section = section,
            rank = int(rank)
            )
        return new_user
    return False
        
def valid_login(request):
    username = request.form['username']
    password = request.form['password']
    
    user = User.query.filter_by(username=username).first()
    if user:
        if check_password_hash(user.password, password):
            return user
        else:
            flash('Incorrect password, try again.')
    else:
        flash('Username does not exist.')
    return False

PrepaGuide-main/app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'

def create_app():
    app = Flask(__name__)
    app.config.from_object('config.Config')
    db.init_app(app)
    login_manager.init_app(app)
    
    # create databases and tables if they do not exist
    from .models import User, Table, Data
    with app.app_context():
        db.create_all()
    
    #import and register blueprints
    from . import auth, routes
    app.register_blueprint(auth.bp)
    app.register_blueprint(routes.bp)   
 
    #return active session
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

PrepaGuide-main/app/auth.py
# prevent browser back button
from flask_login import current_user

from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import login_user, logout_user, login_required
from .forms import valid_sign_up, valid_login
from . import db

bp = Blueprint('auth', __name__, url_prefix='/')

# SIGN UP
@bp.route('/sign_up', methods=('GET', 'POST'))
def sign_up():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    
    if request.method == 'POST':
        new_user = valid_sign_up(request)
        if new_user:
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            return redirect(url_for('main.index'))
    
    return render_template('auth/sign_up.html')

#LOGIN PAGE
@bp.route('/login', methods=('GET', 'POST'))
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    
    if request.method == 'POST':
        user = valid_login(request)
        if user:
            login_user(user)
            return redirect(url_for("main.index"))

    return render_template('auth/login.html')

#LOG OUT        
@login_required
@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

PrepaGuide-main/app/routes.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import login_required, current_user
from .models import User, Table
from .db import ball

bp = Blueprint('main', __name__)

@bp.route('/guide')
def guide():
    return render_template('/guide.html')

@bp.route('/learn_more')
def learn_more():
    return render_template('/learn_more.html')

@bp.route('/', methods=('GET', 'POST')) 
@login_required
def index():
    user = current_user.to_dict()
    rank = user['rank']
    section = user['section']
    
    return render_template('filter/index.html', user=user, ball=ball(rank, section))

PrepaGuide-main/app/templates/base.html
<!DOCTYPE HTML>
<html lang="fr">
	<head>
		<title>Prepa Guide Web App</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="icon" href="{{ url_for('static', filename='images/favicon.png') }}" type="image/x-icon">
		<link rel="stylesheet" href="{{url_for('static', filename='assets/css/main.css') }}" />
		<noscript><link rel="stylesheet" href="{{ url_for('static', filename='assets/css/noscript.css') }}" /></noscript>
	</head>
	<body class="is-preload">
		<!-- Wrapper -->
			<div id="wrapper" class="fade-in">

                <!-- Intro -->
				{%block intro%}{%endblock%}

				<!-- Header -->
				<header id="header">
				    <a href="{{ url_for('main.index') }}" class="logo">Prepa_Guide</a>
				</header>
			
				<!-- Nav bar -->
				<nav id="nav">
                	{%block nav%}{%endblock%}
				</div>	

				<!-- Main -->
				<div id="main">
					{%block main%}{%endblock%}
				</div>
                
                <!-- Footer -->
				<div id="footer">
                	{%block footer%}{%endblock%} 
				</div>

				<!-- Copyright -->
				<div id="copyright">
					<ul><li>&copy; Untitled</li><li>Design: <a href="https://html5up.net">HTML5 UP</a></li></ul>
					<ul><li>&copy; Untitled</li><li>Favicon: <a href="https://www.flaticon.com/free-icons/technology" title="technology icons">Technology icons created by Freepik - Flaticon</a></li></ul>
				</div>

			</div>

		<!-- Scripts -->
			<script src="{{ url_for('static', filename='assets/js/jquery.min.js') }}"></script>
			<script src="{{ url_for('static', filename='assets/js/jquery.scrollex.min.js') }}"></script>
			<script src="{{ url_for('static', filename='assets/js/jquery.scrolly.min.js') }}"></script>
			<script src="{{ url_for('static', filename='assets/js/browser.min.js') }}"></script>
			<script src="{{ url_for('static', filename='assets/js/breakpoints.min.js') }}"></script>
			<script src="{{ url_for('static', filename='assets/js/util.js') }}"></script>
			<script src="{{ url_for('static', filename='assets/js/main.js') }}"></script>
			
			<!-- Personalized functions -->
			<script src="{{ url_for('static', filename='assets/js/extra.js') }}"></script>

	</body>
</html>

PrepaGuide-main/app/templates/filter/index.html
{% extends "base.html" %}

{%block intro%}
<div id="intro">
    <h1>Welcome, <br> Prepa Guide </h1>
    <p>une application qui facilite la procedure d'orientation pour les etudiants tunisiens en cycle preparatoire aux etudes ingenieurs</p>
    <ul class="actions">
        <li><a href="#main" class="button icon solid solo fa-arrow-down scrolly">Continue</a></li>
    </ul>
</div>
{%endblock%}

{%block nav%}
<ul class="links">
    <li class="active"><a>Welcome Home</a></li>
    <li><a href="{{ url_for('main.guide') }}">Guide</a></li>
    <li><a href="{{ url_for('main.learn_more') }}">Learn More</a></li>
</ul>
{%endblock%}

{% block main %}
<h1>Felicitations jeune taupin!</h1>

<ul id="user-data" class="hidden">
    <li id="location">{{user['location']}} </li>
    <li id="filiere">{{user['filiere']}} </li>
    <li id="rank">{{user['rank']}} </li>
</ul>
    
<div class="row gtr-uniform">
    <div class="row gtr-uniform">
        <!--search bar -->
        <div class="col-12 hidden">
            <label for="search">barre de recherche</label>
        </div>
        <div class="col-12 hidden">
            <input type="search" id="searchInput" placeholder="ecole, filiere...">
        </div>

        <!-- search table-->
        <div id="searchTable" class="table-wrapper hidden">
            <table id="searchTable" class="alt">
                <tbody>
                    <div id="searchTable" class="table-wrapper">
                        <table id="searchTable" class="alt">
                            <tbody>
                                <tr> <td>Ecole Nationale d'Ingénieurs de Tunis</td> </tr>
                                <tr> <td>Ecole Nationale d'Ingénieurs de Bizerte</td> </tr>
                                <tr> <td>Ecole Nationale d'Ingénieurs de Sousse</td> </tr>
                                <tr> <td>Ecole Nationale d'Ingénieurs de Monastir</td> </tr>
                                <tr> <td>Ecole Nationale d'Ingénieurs de Sfax</td> </tr>
                                <tr> <td>Ecole Nationale d'Ingénieurs de Gabès</td> </tr>
                                <tr> <td>Faculté des Sciences de Tunis</td> </tr>
                                <tr> <td>Ecole Nationale Supérieure d'Ingénieurs de Tunis</td> </tr>
                                <tr> <td>Ecole Nationale d'ingénieurs de Carthage</td> </tr>
                                <tr> <td>Ecole Nationale d'Electronique et des Télécommunications de Sfax</td> </tr>
                                <tr> <td>Ecole Polytechnique de Tunisie</td> </tr>
                                <tr> <td>Ecole Nationale des Sciences de l'Informatique</td> </tr>
                                <tr> <td>Ecole Supérieure de la statistique et de l'Analyse de l'Information</td> </tr>
                                <tr> <td>École Supérieure des Communications de Tunis</td> </tr>
                                <tr> <td>Ecole Nationale des Sciences et Technologies Avancées De Borj Cedria</td> </tr>
                                <tr> <td>Ecole Nationale d'Ingénieurs de Gafsa</td> </tr>
                                <tr> <td>Institut National Agronomique de Tunisie</td> </tr>
                                <tr> <td>Ecole Supérieure des Industries Alimentaires de Tunis</td> </tr>
                                <tr> <td>Ecole Supérieure d'Ingénieurs de Medjez El Bab</td> </tr>
                                <tr> <td>Ecole Supérieure d'Agriculture de Mateur</td> </tr>
                                <tr> <td>Ecole Supérieure d'Agriculture de Mograne</td> </tr>
                                <tr> <td>Ecole Supérieure d'Agriculture du Kef</td> </tr>
                                <tr> <td>nstitut Supérieur Agronomique de Chott-Mariem</td> </tr>
                                <tr> <td>Génie Chimique- Procédés</td> </tr>
                                <tr> <td>Statistique et Analyse de l'Information</td> </tr>
                                <tr> <td>Electronique Industrielle</td> </tr>
                                <tr> <td>Agro- alimentaire</td> </tr>
                                <tr> <td>Génie des Communications et Réseaux</td> </tr>
                                <tr> <td>Génie Hydraulique et Environnement</td> </tr>
                                <tr> <td>Production Animale</td> </tr>
                                <tr> <td>Génie Electrique- Automatique</td> </tr>
                                <tr> <td>Topographie</td> </tr>
                                <tr> <td>Génie Mécanique</td> </tr>
                                <tr> <td>Génie Informatique Industrielle</td> </tr>
                                <tr> <td>Ingénierie des Données et Systèmes Décisionnels</td> </tr>
                                <tr> <td>Horticulture</td> </tr>
                                <tr> <td>Génie Energétique et Technologies de l'Environnement</td> </tr>
                                <tr> <td>Génie Energétique</td> </tr>
                                <tr> <td>Mécatronique</td> </tr>
                                <tr> <td>Génie Electromécanique</td> </tr>
                                <tr> <td>Génie Chimique Industriel et Minier</td> </tr>
                                <tr> <td>Génie des Systèmes Horticoles</td> </tr>
                                <tr> <td>Génie des Systèmes Industriels et Logistiques</td> </tr>
                                <tr> <td>Production Animale et Fourragère</td> </tr>
                                <tr> <td>Génie Mathématiques Appliquées et Modélisation</td> </tr>
                                <tr> <td>Génie Rural, Eaux et Forêts</td> </tr>
                                <tr> <td>Télécommunications</td> </tr>
                                <tr> <td>Génie Productique</td> </tr>
                                <tr> <td>Polytechnique</td> </tr>
                                <tr> <td>Hydraulique et Amenagement</td> </tr>
                                <tr> <td>Modélisation pour l'Industrie et Services</td> </tr>
                                <tr> <td>Génie des Systèmes Electroniques et Communications</td> </tr>
                                <tr> <td>Génie Informatique</td> </tr>
                                <tr> <td>Techniques Avancées</td> </tr>
                                <tr> <td>Génie Civil</td> </tr>
                                <tr> <td>Génie Electrique</td> </tr>
                                <tr> <td>Génie des Matériaux et Management Industriel</td> </tr>
                                <tr> <td>Génie Textile</td> </tr>
                                <tr> <td>Technologies Avancées</td> </tr>
                                <tr> <td>Chimie Analytique et Instrumentation</td> </tr>
                                <tr> <td>Informatique Appliquée</td> </tr>
                                <tr> <td>Génie Télécommunications Embarquées</td> </tr>
                                <tr> <td>Génie des Télécommunications</td> </tr>
                                <tr> <td>Informatique</td> </tr>
                                <tr> <td>Génie Industriel</td> </tr>
                                <tr> <td>Génie Mécanique et Agro-Industriel</td> </tr>
                                <tr> <td>Aménagement du Paysage</td> </tr>
                                <tr> <td>Infotronique</td> </tr>
                            </tbody>
                        </table>
                    </div>
                </tbody>
            </table>
        </div>

        <!-- Field buttons -->
        <div class="col-12">
            <label for="field">Filtrer par categorie</label>
            <ul class="filtring-btn">
                <li><button class="button fit small" value="all">Tout</button></li>
                <li><button class="button fit small" value="Computer Science and IT">Informatique et Technologies de l'Information</button></li>
                <li><button class="button fit small" value="Energy, Industrial Engineering and Management">Énergie, Génie Industriel et Management</button></li>
                <li><button class="button fit small" value="Mechanical, Electrical and Civil Engineering">Génie Mécanique, Électrique et Civil</button></li>
                <li><button class="button fit small" value="Chemical and Biological Engineering">Génie Chimique et Biologique</button></li>
                <li><button class="button fit small" value="Agricultural and Environmental Engineering">Génie Agricole et Environnemental</button></li>
                <li><button class="button fit small" value="Textile and Material Engineering">Génie Textile et des Matériaux</button></li>
                <li><button class="button fit small" value="Mathematics and Statistics">Mathématiques et Statistiques</button></li>
                <li><button class="button fit small" value="OTHER"> AUTRE</button></li>
            </ul>
        </div>

        <!-- Sliders -->
        <div class="col-6">
            <label for="leniency">Tolerance: <span id="tsliderValue">50</span></label>
            <input type="range" id="tSlider" class="slider" min="1" max="100" />
        </div>
        <div class="col-6">
            <label for="distance">Proximité: <span id="psliderValue">50</span></label>
            <input type="range" id="pSlider" class="slider" min="1" max="500" />
        </div>
</div>


<!-- Desktop Table -->
<div id="table" class="table-wrapper desktop-table">
    <h3>Liste des Choix</h3>
    <table class="table-sortable">
        <thead>
            <tr>
                <th>Ecole</th>
                <th>Filiere</th>
                <th>Gouvernorat</th>
                <th>Rang</th>
                <th>Diff</th>
            </tr>
        </thead>
        <tbody>
            {%for row in ball%}
            <tr>
                <td>{{row[1]}}</td>
                <td>{{row[2]}}</td>
                <td>{{row[3]}}</td>
                <td>{{row[5]}}</td>
                <td>{{row[-1]}}%</td>
            </tr>
            {%endfor%}
        </tbody>
    </table>

    <!-- Back Up button -->
    <div class="col-12">
        <ul class="actions fit">
            <li><a href="#main" class="button primary fit icon solid fa-arrow-up scrolly">BACK UP</a></li>
        </ul>
    </div>
</div>
{% endblock %}

PrepaGuide-main/app/templates/guide.html
{% extends "base.html" %}

{%block nav%}
<ul class="links">
    <li><a href=" {{ url_for('auth.login') }} ">Acceuil</a></li>
    <li class="active"><a href="{{ url_for('main.guide') }}">Guide</a></li>
    <li><a href="{{ url_for('main.learn_more') }}">Learn More</a></li>
</ul>
{%endblock%}

{%block main%}
<section class="post">
    <header class="major">
        <h1><a href="#" alt="telecharger le guide">Guide du candidat</a></h1>
    </header>

    <ul class="links"> 
        <li><a href="#Q1" class="scrolly">1. Comment choisir sa filière ou son établissement de formation d'ingénieurs?</a></li>
        <li><a href="#Q2" class="scrolly">2. Quelle importance accorder à la fiche de confirmation ?</a></li>
        <li><a href="#Q3" class="scrolly">3. Comment s'effectue l'affectation définitive des candidats aux établissements de formation d'ingénieurs ?</a></li>
    </ul>    
</section> 

<header>
    <h2 id="Q1">1. Comment choisir sa filière ou son établissement de formation d'ingénieurs? </h2>
    <p>Lors de la proclamation des résultats d'admission, les candidats de la liste des admis et de la liste 
        complémentaire doivent remplir des fiches de choix des filières des établissements concernés par chaque 
        concours, disponibles sur le <a href="https://concours-ingenieurs.rnu.tn">site</a> dans les délais qui sont mentionnés 
        sur le même site. </p>
    <p>Quatre formes de fiches de choix sont mises à la disposition des candidats de chaque concours, Le candidat numérote les filières 
        des institutions choisies par ordre de préférence.
        <div class="row">
            <ol>
                <li>Fiche destinée aux candidats classés parmi les 25% les plus méritants de la liste des admis. 
                    Ces candidats sont tenus de choisir un nombre minimal de filières parmi l'ensemble des filières 
                    des institutions proposées. </li>
                <li>Fiche concernant les candidats classés entre 25% et 60% de la liste des admis. Ces candidats 
                    sont obligés d'y inscrire un nombre de choix, supérieur au nombre minimal de choix demandé 
                    au groupe de candidats cité précédemment. </li>
                <li>Fiche réservée pour le reste des candidats de la liste des admis, classés entre 60% 
                    et 100%. Ces candidats doivent nécessairement classer toutes les filières ouvertes des 
                    différents établissements concernés par le concours. </li>
                <li>Fiche destinée aux candidats de la liste complémentaire qui sont tenus de classer toutes les 
                    filières ouvertes des différents établissements concernés par le concours. </li>
            </ol>
        </div>   
    </p>    
</header>
<header>
    <h2 id="Q2">2. Quelle importance accorder à la fiche de confirmation ? </h2>
    <p>Lors de la proclamation des résultats d'affectation, les candidats admis et affectés à une filière d'un 
        établissement donné sont tenus, sous peine de perdre le bénéfice du résultat obtenu, de confirmer, sur 
        le <a href="https://concours-ingenieurs.rnu.tn">site</a>, le choix retenu ainsi que les filières pour lesquelles ils figurent 
        sur leurs listes d'attente, dans les délais qui sont mentionnés sur le même site. 
        <p>Les candidats de la liste complémentaire sont obligés de confirmer leurs places dans les listes d'attente 
        sous peine de perdre le bénéfice d'une possible affectation suite aux désistements de certains candidats 
        de la liste des admis. 
        Le candidat qui ne procède pas à cette opération est écarté du concours et perd le résultat obtenu. </p>
    </p>    
    </header>
<header>
    <h2 id="Q3">3. Comment s'effectue l'affectation définitive des candidats aux établissements de formation d'ingénieurs ? </h2>
    <p>A l'expiration du délai de confirmation et sur la base des confirmations reçues, le jury des concours arrête 
        la liste définitive des admis affectés aux différentes filières proposées, et ce dans la limite des places 
        ouvertes, en faisant bénéficier éventuellement les candidats de la liste des admis d'un meilleur choix et les candidats les mieux classés de la liste complémentaire 
        des places non pourvues. <b>La validité des listes d'attente s'achève avec la proclamation des résultats 
        définitifs.</b></p>
    <p>
        Le traitement des confirmations se déroule en tenant compte des trois cas de figure suivants
        <div class="row">
            <ul>
                <li><b>Candidat déclaré admis à une filière de formation d'ingénieurs et ne figurant sur aucune 
                    liste d'attente:</b> si le candidat confirme son admission, il est affecté à cette filière. Dans le cas 
                    contraire il sera éliminé du concours. </li>
                <li><b>Candidat déclaré admis à une filière de formation d'ingénieurs et inscrit sur une ou 
                    plusieurs listes d'attente:</b> trois cas de confirmation peuvent se présenter
                    <div>
                        <ul>
                            <li>le candidat confirme uniquement son admission à la filière et renonce aux listes 
                                d'attente : il sera alors affecté à la filière à laquelle il est déclaré admis. </li>   
                            <li>le candidat confirme son admission ainsi que son inscription sur une ou plusieurs 
                                listes d'attente : si le nombre de places non pourvues le permet, il sera affecté au meilleur 
                                choix possible de sa liste de vœux parmi les résultats confirmés. Dans le cas contraire, il sera 
                                affecté à la filière à laquelle il est déclaré admis. </li>    
                            <li>le candidat ne confirme pas son admission et confirme seulement son inscription sur 
                                une ou plusieurs listes d'attente : si le nombre de places non pourvues le permet, il sera 
                                affecté au meilleur choix possible de sa liste de vœux parmi les résultats confirmés. Dans le 
                                cas contraire, il sera éliminé du concours. </li>     
                        </ul>
                    </div>
                </li>
                <li><b>Candidat uniquement inscrit sur une ou plusieurs listes d'attente :</b> s'il confirme son 
                    inscription sur une ou plusieurs de ces listes et si le nombre de places non pourvues le permet, 
                    il sera affecté au meilleur choix possible de sa liste de vœux parmi les résultats confirmés. Dans 
                    le cas contraire, il sera éliminé du concours. </li>
            </ul>
        </div>    
    </p>
    <p>Il est important de rappeler que si, après confirmation, un candidat est affecté à une filière de 
        formation d'ingénieurs, il ne pourra plus se représenter aux concours nationaux d'entrée aux 
        cycles de formation d'ingénieurs. Il ne pourra pas non plus demander une mutation vers une autre 
        école de formation d'ingénieurs ou une autre filière. </p>
    <p>
        Les résultats définitifs sont portés à la connaissance des candidats par affichage sur le site <a href="https://concours-ingenieurs.rnu.tn">site</a>. Ainsi,
        <ul>
            <li>au secrétariat des concours</li>
            <li>à chaque établissement, centre d'examen</li>
        </ul>
        <b>Les résultats définitifs ne sont susceptibles d'aucun changement pour quelque motif que ce soit.</b>
    </p>    
</header>
{%endblock%}

PrepaGuide-main/app/templates/learn_more.html
{% extends "base.html" %}

{%block nav%}
<ul class="links">
    <li><a href=" {{ url_for('auth.login') }} ">Acceuil</a></li>
    <li><a href="{{ url_for('main.guide') }}">Guide</a></li>
    <li class="active"><a href="{{ url_for('main.learn_more') }}">Learn More</a></li>
</ul>
{%endblock%}

{%block main%}{%endblock%}

{%block footer%}{%endblock%}